### ISSUE TITLE
Stopping Navigation based on logic within `OnLeavingAsync`

### ISSUE THREAD

**Issue by mcanyucel** [nalu-development/nalu#41]
### Describe the feature

I am trying to put a verification when the user is trying to leave a page with form data. Is there a way to put a verification  question and then cancel the navigation within the `OnLeavingAsync` implementation? Something in the lines of :

```csharp
        if (!isLeaveAfterSaving)
        {
            await notificationService.ShowQuestion(
            "Go Back",
            "This will discard all the changes. Are you sure?",
            "Yes",
            "No",
            () => {},
            () => e.Cancel = true );
        }
```
When I am navigating away from the page, I can put this code within my own app logic but when the user taps the back button on the navigation bar, I am not sure how to stop them outside of hiding the button.

**Comment by sumowesley** [comment]
Does implementing the ILeavingGuard interface not help?

**Comment by mcanyucel** [comment]
right, I misunderstood the `ILeavingGuard` completely. I thought it was for a completely different purpose (I don't know why). Thanks for the direction! Closing this issue.

**Comment by albyrock87** [comment]
@mcanyucel do you have any suggestions on how I could improve the documentation to make `ILeavingGuard` easier to understand?

**Comment by mcanyucel** [comment]
>Sometimes you want to protect a page from being popped from the navigation stack, for example when the user is editing a form. You can do that by implementing the ILeavingGuard interface which defines a ValueTask<bool> CanLeaveAsync() method from which you can eventually display a prompt to ask the user if they want to leave the page.

Actually this section explains it quite nicely, but a sample code will help much more. I think the reason I misunderstood was it is a single short paragraph, kind of between sections that explain different things, so people might skip it without understanding it. (well, that's what I did.)

Enhancing the section with a simple sample code will help, something in the lines of;

```csharp 
public class ViewModel :  ILeavingGuard
{
    public ValueTask<bool> CanLeaveAsync()
    {
        return await ConfirmUserLeave() // a method to verify the leave action
    }
}
```

**Comment by albyrock87** [comment]
Thanks for your suggestion @mcanyucel https://github.com/nalu-development/nalu/commit/cb3a7205f6ebe04148710d1e39c6f6030ed60f7a
