### ISSUE TITLE
Getting error after installing Nalu.Maui in Maui Library

### ISSUE THREAD

**Issue by HobDev** [nalu-development/nalu#5]
### Describe the bug

One or more duplicate file names were detected.  All image output filenames must be unique: nalu_navigation_arrow_back_android (C:\Users\spara\.nuget\packages\nalu.maui\1.1.1\buildTransitive\\Images\nalu_navigation_arrow_back_android.svg), nalu_navigation_arrow_back_ios (C:\Users\spara\.nuget\packages\nalu.maui\1.1.1\buildTransitive\\Images\nalu_navigation_arrow_back_ios.svg), nalu_navigation_menu (C:\Users\spara\.nuget\packages\nalu.maui\1.1.1\buildTransitive\\Images\nalu_navigation_menu.svg)	Milker.Milkman	C:\Users\spara\.nuget\packages\microsoft.maui.resizetizer\8.0.6\buildTransitive\Microsoft.Maui.Resizetizer.After.targets	623	

### Steps to reproduce

I am using a Maui library which is shared with the Maui Blazor Hybrid project. I installed the Nalu.Maui NuGet to Maui Library project so that I can use it other projects referencing the library. But the error is preventing the build.

### Expected behaviour

I want to build and deploy the project to Android Emulator

**Comment by albyrock87** [comment]
@HobDev thanks for the bug report and for trying out Nalu.Maui!!

This should now be fixed in 1.1.2, in case it's not please reopen the issue and provide a sample project to reproduce the issue.
